apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/api-demolyment.yaml
- ../../../base/api-ingress.yaml
- ../../../base/api-service.yaml

images:
- name: muve-api
  newName: 816208829212.dkr.ecr.ap-northeast-2.amazonaws.com/muve-api-repo
  newTag: "116"

namespace: default