apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-deployment.yaml
- api-ingress.yaml
- api-service.yaml
- api-external-secret.yaml
- ../../../base

images:
- name: muve-api
  newName: 816208829212.dkr.ecr.ap-northeast-2.amazonaws.com/muve-api-repo
  newTag: "126"
namespace: default
