apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-options: Replace=true
# metadata:
  # annotations:
  #   argocd.argoproj.io/sync-options: Replace=true

resources:
- api-deployment.yaml
- api-ingress.yaml
- api-service.yaml
- api-external-secret.yaml
- ../../../base

images:
- name: muve-api
  newName: 816208829212.dkr.ecr.ap-northeast-2.amazonaws.com/muve-api-repo
  newTag: "133"

namespace: default
