apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-api-secrets-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret-access-keys
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-secret-access-keys
            key: secret-access-key