apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: muve-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/muve-team/muve-helm.git'
    targetRevision: HEAD
    path: overlays/prod/muve-api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: muve-admin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/muve-team/muve-helm.git'
    targetRevision: HEAD
    path: overlays/prod/muve-admin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: muve-mall
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/muve-team/muve-helm
    targetRevision: main
    path: overlays/prod
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true