apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: default

secretGenerator:
- name: muve-api-secrets
  envs:
  - .env.api
- name: muve-admin-secrets
  envs:
  - .env.admin