apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-options: Replace=true

resources:
- mall-deployment.yaml
- mall-ingress.yaml
- mall-service.yaml
- mall-external-secret.yaml
- mall-secret-store.yaml

images:
- name: muve-mall
  newName: 816208829212.dkr.ecr.ap-northeast-2.amazonaws.com/muve-mall-repo
  newTag: "192"

namespace: default
