apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: muve-mall-environment-keys
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-mall-secrets-store
    kind: SecretStore
  target:
    name: muve-mall-environment-keys
  data:
    - secretKey: DB_URL
      remoteRef:
        key: /aws/secret/muve-environment-keys-1
        property: DB_URL
    - secretKey: DB_USERNAME
      remoteRef:
        key: /aws/secret/muve-environment-keys-1
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /aws/secret/muve-environment-keys-1
        property: DB_PASSWORD
    - secretKey: AWS_S3_ACCESS_KEY_ID
      remoteRef:
        key: /aws/secret/muve-environment-keys-1
        property: AWS_S3_ACCESS_KEY_ID
    - secretKey: AWS_S3_SECRET_ACCESS_KEY
      remoteRef:
        key: /aws/secret/muve-environment-keys-1
        property: AWS_S3_SECRET_ACCESS_KEY
    - secretKey: ELASTIC_SEARCH_URL
      remoteRef:
        key: /aws/secret/muve-environment-keys-1
        property: ELASTIC_SEARCH_URL
    - secretKey: ELASTIC_SEARCH_USERNAME
      remoteRef:
        key: /aws/secret/muve-environment-keys-1
        property: ELASTIC_SEARCH_USERNAME
    - secretKey: ELASTIC_SEARCH_PASSWORD
      remoteRef:
        key: /aws/secret/muve-environment-keys-1
        property: ELASTIC_SEARCH_PASSWORD