apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admin-deployment.yaml
  - admin-ingress.yaml
  - admin-service.yaml

images:
- name: muve-admin
  newName: 816208829212.dkr.ecr.ap-northeast-2.amazonaws.com/muve-admin-repo
  newTag: "116"

namespace: default

bases:
  - ../../../base