apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-options: Replace=true

resources:
- admin-deployment.yaml
- admin-ingress.yaml
- admin-service.yaml
- admin-external-secret.yaml
- admin-secret-store.yaml

images:
- name: muve-admin
  newName: 816208829212.dkr.ecr.ap-northeast-2.amazonaws.com/muve-admin-repo
  newTag: "202"

namespace: default
