apiVersion: apps/v1
kind: Deployment
metadata:
  name: muve-admin
  labels:
    app: muve-admin
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: muve-admin
  template:
    metadata:
      labels:
        app: muve-admin
    spec:
      containers:
      - name: muve-admin
        image: muve-admin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
        - name: DB_URL
          value: {{ .Values.env.DB_URL | quote }}
        - name: DB_USERNAME
          value: {{ .Values.env.DB_USERNAME | quote }}
        - name: DB_PASSWORD
          value: {{ .Values.env.DB_PASSWORD | quote }}
        - name: AWS_S3_ACCESS_KEY_ID
          value: {{ .Values.env.AWS_S3_ACCESS_KEY_ID | quote }}
        - name: AWS_S3_SECRET_ACCESS_KEY
          value: {{ .Values.env.AWS_S3_SECRET_ACCESS_KEY | quote }}
        - name: SERVER_PORT
          value: {{ .Values.env.SERVER_PORT | quote }}
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
