apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    {{- include "muve.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.admin.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: muve-admin
