apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    {{- include "muve.labels" . | nindent 4 }}
    app: muve-admin
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      app: muve-admin
  template:
    metadata:
      labels:
        app: muve-admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.admin.resources | nindent 12 }}
          env:
            - name: DB_URL
              value: {{ .Values.global.DB_URL | quote }}
            - name: DB_USERNAME
              value: {{ .Values.global.DB_USERNAME | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.global.DB_PASSWORD | quote }}
            - name: AWS_S3_ACCESS_KEY_ID
              value: {{ .Values.global.AWS_S3_ACCESS_KEY_ID | quote }}
            - name: AWS_S3_SECRET_ACCESS_KEY
              value: {{ .Values.global.AWS_S3_SECRET_ACCESS_KEY | quote }}
