apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "muve.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: muve-api
