apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-deployment.yaml
- api-service.yaml
- api-ingress.yaml
- admin-deployment.yaml
- admin-service.yaml
- admin-ingress.yaml