replicas: 1
containerPort: 8082
serverPort: 8082
image:
  repository: 816208829212.dkr.ecr.ap-northeast-2.amazonaws.com/muve-api-repo
  tag: latest
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"
env:
  SPRING_PROFILES_ACTIVE: ""
  DB_URL: ""
  DB_USERNAME: ""
  DB_PASSWORD: ""
  AWS_S3_ACCESS_KEY_ID: ""
  AWS_S3_SECRET_ACCESS_KEY: ""
  SERVER_PORT: ""